name: handles-decentralized-minting
on:
  push:
    branches:
      - master
jobs:
  deploy:
    if: github.repository_owner == 'koralabs'
    name: Deploying from ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install Libssl
        run: |
          wget https://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb

      - name: Install Aiken
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://install.aiken-lang.org | sh
          ~/.aiken/bin/aikup install v1.0.29-alpha
          sudo ln -s ~/.aiken/bin/aiken /usr/local/bin/aiken

      - name: Publish ${{ github.workflow }}
        id: publish
        env:
          DEPLOYMENT_ACCESS_TOKEN: ${{ secrets.DEPLOYMENT_ACCESS_TOKEN }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          VARS_CONTEXT: ${{ toJson(vars) }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          DEPLOYMENT_TYPE: npm-publish
          NODE_VERSION: 20
          IS_PUBLIC: true
        run: |
          set -eu
          curl -H "Authorization: Bearer ${DEPLOYMENT_ACCESS_TOKEN}" https://raw.githubusercontent.com/koralabs/adahandle-deployments/master/common/main.sh -o main.sh
          chmod +x main.sh && ./main.sh
